rewardEpochInterval = 75
eth1Endpoint = "xxxxx"
eth2Endpoint = "xxxxxx"
logFilePath = ""
version = "dev"          # v1 v2 dev
slashStartEpoch = 898

[contracts]
storageContractAddress = "0xA4efE44eE3D52211df575b9fD8F3409C5c1443eE"

[db]
host = "127.0.0.1" # mysql host ip
name = "eth2_dev"  # the database this server used
port = "3306"
pwd = "123456"     # mysql password
user = "root"      # mysql username
