eth1Endpoint = "" 
eth2Endpoint = "" 
fakeBeaconNode = true 
from = "0xB20e8393C07FC446D17277c80b8E3f82Cd857A50" 
gasLimit = "3000000" 
keystorePath = "./keys" 
listenAddr = ":80" 
logFilePath = "" 
maxGasPrice = "30000000000" #wei
rateSlotInterval = 10 
startEpoch = 0 
startHeight = 0 

[contracts]
storageContractAddress = "0xA4efE44eE3D52211df575b9fD8F3409C5c1443eE"

[db]
host = "127.0.0.1" # mysql host ip
name = "eth2" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username
