eth1Endpoint = "https://rpc.zhejiang.ethpandaops.io"
eth2Endpoint = "https://beacon-lighthouse-zhejiang.stafi.io"
logFilePath = ""
gasLimit = "3000000"
keystorePath = "./keys"
maxGasPrice = "60000000000"                                  #wei

[contracts]
storageContractAddress = "0x126d3C08Fb282d5417793B7677E3F7DA8347A384"
