eth1Endpoint = "https://rpc.zhejiang.ethpandaops.io"
eth2Endpoint = "https://beacon-lighthouse-zhejiang.stafi.io"
logFilePath = ""
version = "dev"                                              # v1 v2 dev

[contracts]
storageContractAddress = "0x126d3C08Fb282d5417793B7677E3F7DA8347A384"

[db]
host = "127.0.0.1" # mysql host ip
name = "eth2_dev"  # the database this server used
port = "3306"
pwd = "123456"     # mysql password
user = "root"      # mysql username
