listenAddr = ":8083"
logFilePath = ""
unstakingStartTimestamp = 1675973448
stafiInfoEndpoint = "https://rtoken-api2.stafi.io"

[db]
host = "127.0.0.1" # mysql host ip
name = "eth2_dev"  # the database this server used
port = "3306"
pwd = "123456"     # mysql password
user = "root"      # mysql username
