eth1Endpoint = "https://rpc.zhejiang.ethpandaops.io"
eth2Endpoint = "https://beacon.zhejiang.ethpandaops.io"
from = "0xB20e8393C07FC446D17277c80b8E3f82Cd857A50"
gasLimit = "3000000"
keystorePath = "./keys"
logFilePath = ""
maxGasPrice = "60000000000"                             #wei

[contracts]
storageContractAddress = "0x126d3C08Fb282d5417793B7677E3F7DA8347A384"

[db]
host = "127.0.0.1" # mysql host ip
name = "eth2_dev"  # the database this server used
port = "3306"
pwd = "123456"     # mysql password
user = "root"      # mysql username
