// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "tpkeeper",
            "email": "tpkeeper.me@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/exitElectionList": {
            "post": {
                "description": "exit election list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "exit election list",
                "parameters": [
                    {
                        "description": "election list",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqExitElectionList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspExitElectionList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/gasPrice": {
            "get": {
                "description": "gas price",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "gas price",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspGasPrice"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/nodeInfo": {
            "post": {
                "description": "node info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "node info",
                "parameters": [
                    {
                        "description": "node info",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqNodeInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspNodeInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/notifyMsgList": {
            "post": {
                "description": "notify node msg list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "notify msg list",
                "parameters": [
                    {
                        "description": "notify msg",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqNotifyMsgList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspNotifyMsgList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/poolData": {
            "get": {
                "description": "pool data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "pool data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspPoolData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/proof": {
            "post": {
                "description": "proof",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "get proof of claim",
                "parameters": [
                    {
                        "description": "proof",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqProof"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspProof"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/proposeElectionList": {
            "post": {
                "description": "propose election list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "propose election list",
                "parameters": [
                    {
                        "description": "election list",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqProposeElectionList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspProposeElectionList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/pubkeyDetail": {
            "post": {
                "description": "pubkey detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "pubkey detail",
                "parameters": [
                    {
                        "description": "pubkey detail",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqPubkeyDetail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspPubkeyDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/pubkeyStatusList": {
            "post": {
                "description": "pubkey status list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "pubkey status list",
                "parameters": [
                    {
                        "description": "pubkey status list",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqPubkeyStatusList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspPubkeyStatusList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/rewardInfo": {
            "post": {
                "description": "reward info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "reward info",
                "parameters": [
                    {
                        "description": "reward info",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqRewardInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspRewardInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staker/unstakingLeftSeconds": {
            "get": {
                "description": "unstaking left seconds",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "staker unstaking left seconds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/staker_handlers.RspUnstakingLeftSeconds"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staker/unstakingPlanExist": {
            "post": {
                "description": "staker unstaking plan exit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "unstaking plan exit",
                "parameters": [
                    {
                        "description": "unstaking plan exist",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staker_handlers.ReqUnstakingPlanExist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/staker_handlers.RspUnstakingPlanExist"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staker/uploadUnstakingPlan": {
            "post": {
                "description": "staker unstaking plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "unstaking plan",
                "parameters": [
                    {
                        "description": "unstaking plan",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staker_handlers.ReqUploadUnstakingPlan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Rsp"
                        }
                    }
                }
            }
        },
        "/v1/staker/withdrawRemainingTime": {
            "post": {
                "description": "staker withdraw remaining time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "staker withdraw remaining time",
                "parameters": [
                    {
                        "description": "staker address",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/staker_handlers.ReqWithdrawRemainingTime"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/staker_handlers.RspWithdrawRemainingTime"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/unstakePoolData": {
            "get": {
                "description": "unstake pool data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "unstake pool data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspUnstakePoolData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/withdrawInfo": {
            "post": {
                "description": "withdraw info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "withdraw info",
                "parameters": [
                    {
                        "description": "withdraw info",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/node_handlers.ReqWithdrawInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/node_handlers.RspWithdrawInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "node_handlers.ExitElection": {
            "type": "object",
            "properties": {
                "choosenTime": {
                    "type": "integer"
                },
                "ethReward": {
                    "type": "string"
                },
                "exitTime": {
                    "type": "integer"
                },
                "publicKey": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ProposeElection": {
            "type": "object",
            "properties": {
                "choosenTime": {
                    "type": "integer"
                },
                "ethReward": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ReqExitElectionList": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "type": "string"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ReqNodeInfo": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "type": "string"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "status": {
                    "description": "ignore if statusList not empty",
                    "type": "integer"
                },
                "statusList": {
                    "description": "{9 active 10 exited 20 pending 30 slash}",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "node_handlers.ReqNotifyMsgList": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "description": "hex string",
                    "type": "string"
                }
            }
        },
        "node_handlers.ReqProof": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "type": "string"
                }
            }
        },
        "node_handlers.ReqProposeElectionList": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "type": "string"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ReqPubkeyDetail": {
            "type": "object",
            "properties": {
                "chartDuSeconds": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                },
                "pubkey": {
                    "description": "hex string",
                    "type": "string"
                }
            }
        },
        "node_handlers.ReqPubkeyStatusList": {
            "type": "object",
            "properties": {
                "pubkeyList": {
                    "description": "hex string list",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "node_handlers.ReqRewardInfo": {
            "type": "object",
            "properties": {
                "chartDuSeconds": {
                    "type": "integer"
                },
                "nodeAddress": {
                    "description": "hex string",
                    "type": "string"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ReqWithdrawInfo": {
            "type": "object",
            "properties": {
                "nodeAddress": {
                    "description": "hex string",
                    "type": "string"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageIndex": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ResNotifyMsg": {
            "type": "object",
            "properties": {
                "msgType": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ResPubkey": {
            "type": "object",
            "properties": {
                "pubkey": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.ResReward": {
            "type": "object",
            "properties": {
                "commission": {
                    "type": "integer"
                },
                "selfEraRewardEth": {
                    "type": "string"
                },
                "selfStakedEth": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "totalEraRewardEth": {
                    "type": "string"
                },
                "totalStakedEth": {
                    "type": "string"
                }
            }
        },
        "node_handlers.ResWithdraw": {
            "type": "object",
            "properties": {
                "depositAmount": {
                    "type": "string"
                },
                "explorerUrl": {
                    "type": "string"
                },
                "operateTimestamp": {
                    "type": "integer"
                },
                "receivedAddress": {
                    "type": "string"
                },
                "rewardAmount": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timeLeft": {
                    "type": "integer"
                },
                "totalAmount": {
                    "type": "string"
                }
            }
        },
        "node_handlers.RspExitElectionList": {
            "type": "object",
            "properties": {
                "electionList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ExitElection"
                    }
                },
                "electionTotalCount": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.RspGasPrice": {
            "type": "object",
            "properties": {
                "baseFee": {
                    "type": "integer"
                },
                "ethPrice": {
                    "type": "number"
                },
                "priorityFee": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.RspNodeInfo": {
            "type": "object",
            "properties": {
                "activeCount": {
                    "type": "integer"
                },
                "ethPrice": {
                    "type": "number"
                },
                "exitedCount": {
                    "type": "integer"
                },
                "pendingCount": {
                    "type": "integer"
                },
                "pubkeyList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ResPubkey"
                    }
                },
                "selfDepositedEth": {
                    "type": "string"
                },
                "selfRewardEth": {
                    "type": "string"
                },
                "slashCount": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalManagedEth": {
                    "type": "string"
                }
            }
        },
        "node_handlers.RspNotifyMsgList": {
            "type": "object",
            "properties": {
                "msgList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ResNotifyMsg"
                    }
                }
            }
        },
        "node_handlers.RspPoolData": {
            "type": "object",
            "properties": {
                "allEth": {
                    "description": "staker principal + validator principal + reward",
                    "type": "string"
                },
                "depositedEth": {
                    "description": "staker principal + validator principal",
                    "type": "string"
                },
                "ethPrice": {
                    "type": "number"
                },
                "matchedValidators": {
                    "description": "staked waiting actived",
                    "type": "integer"
                },
                "mintedREth": {
                    "type": "string"
                },
                "poolEth": {
                    "description": "staker principal + validator principal + reward",
                    "type": "string"
                },
                "stakeApr": {
                    "type": "number"
                },
                "stakedEth": {
                    "description": "matched number * 32 + solo unmatched number * 4 + trust unmatched number * 1",
                    "type": "string"
                },
                "unmatchedEth": {
                    "description": "userdeposit balance",
                    "type": "string"
                },
                "validatorApr": {
                    "type": "number"
                }
            }
        },
        "node_handlers.RspProof": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "proof": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "remainingSeconds": {
                    "type": "integer"
                },
                "totalExitDepositAmount": {
                    "type": "string"
                },
                "totalRewardAmount": {
                    "type": "string"
                }
            }
        },
        "node_handlers.RspProposeElectionList": {
            "type": "object",
            "properties": {
                "electionList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ProposeElection"
                    }
                },
                "electionTotalCount": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.RspPubkeyDetail": {
            "type": "object",
            "properties": {
                "activeDays": {
                    "type": "integer"
                },
                "activeEpoch": {
                    "type": "integer"
                },
                "apr": {
                    "type": "number"
                },
                "chartXData": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chartYData": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "currentBalance": {
                    "type": "string"
                },
                "depositBalance": {
                    "type": "string"
                },
                "effectiveBalance": {
                    "type": "string"
                },
                "eligibleDays": {
                    "type": "integer"
                },
                "eligibleEpoch": {
                    "type": "integer"
                },
                "ethPrice": {
                    "type": "number"
                },
                "last24hRewardEth": {
                    "type": "string"
                },
                "nodeDepositAmount": {
                    "type": "string"
                },
                "slashEventList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.SlashEvent"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalSlashAmount": {
                    "type": "string"
                }
            }
        },
        "node_handlers.RspPubkeyStatusList": {
            "type": "object",
            "properties": {
                "nodeDepositAmountList": {
                    "description": "decimals 18",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "statusList": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "node_handlers.RspRewardInfo": {
            "type": "object",
            "properties": {
                "chartXData": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "chartYData": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ethPrice": {
                    "type": "number"
                },
                "lastEraRewardEth": {
                    "type": "string"
                },
                "rewardList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ResReward"
                    }
                },
                "totalCount": {
                    "type": "integer"
                },
                "totalStakedEth": {
                    "type": "string"
                }
            }
        },
        "node_handlers.RspUnstakePoolData": {
            "type": "object",
            "properties": {
                "ejectedValidators": {
                    "type": "integer"
                },
                "poolEth": {
                    "type": "string"
                },
                "todayUnstakedEth": {
                    "type": "string"
                },
                "unstakeableEth": {
                    "type": "string"
                },
                "waitingStakers": {
                    "type": "integer"
                }
            }
        },
        "node_handlers.RspWithdrawInfo": {
            "type": "object",
            "properties": {
                "totalCount": {
                    "type": "integer"
                },
                "withdrawList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node_handlers.ResWithdraw"
                    }
                }
            }
        },
        "node_handlers.SlashEvent": {
            "type": "object",
            "properties": {
                "endBlock": {
                    "type": "integer"
                },
                "explorerUrl": {
                    "type": "string"
                },
                "slashAmount": {
                    "type": "string"
                },
                "slashType": {
                    "type": "integer"
                },
                "startBlock": {
                    "type": "integer"
                },
                "startTimestamp": {
                    "type": "integer"
                }
            }
        },
        "staker_handlers.ReqUnstakingPlanExist": {
            "type": "object",
            "properties": {
                "stakerAddress": {
                    "description": "hex string",
                    "type": "string"
                }
            }
        },
        "staker_handlers.ReqUploadUnstakingPlan": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "stakerAddress": {
                    "description": "hex string",
                    "type": "string"
                }
            }
        },
        "staker_handlers.ReqWithdrawRemainingTime": {
            "type": "object",
            "properties": {
                "stakerAddress": {
                    "description": "hex string",
                    "type": "string"
                }
            }
        },
        "staker_handlers.RspUnstakingLeftSeconds": {
            "type": "object",
            "properties": {
                "leftSeconds": {
                    "description": "staked waiting actived",
                    "type": "integer"
                }
            }
        },
        "staker_handlers.RspUnstakingPlanExist": {
            "type": "object",
            "properties": {
                "exist": {
                    "type": "boolean"
                }
            }
        },
        "staker_handlers.RspWithdrawRemainingTime": {
            "type": "object",
            "properties": {
                "remainingSeconds": {
                    "description": "staked waiting actived",
                    "type": "integer"
                }
            }
        },
        "utils.Rsp": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/reth",
	Schemes:          []string{},
	Title:            "reth API",
	Description:      "reth api document.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
